### PR TITLE
GitHub stream

### PR DESCRIPTION
**Pull request by cjlee1**
added edit post feature

### CODE REVIEW

**Comment by tiakindele** [comment]
looks good. i'd check with @peterweckend about the migrations files you deleted though.

**Comment by peterweckend** [comment]
Agreed it looks good but can you prevent any migration file changes from showing up in the PR since there was no change to the model? Concerned that an changes to those files will cause heroku to break again

**Comment by peterweckend** [comment]
if you can't find any easy way to remove those from appearing in the PR, you can just merge and ill reset heroku again

**Comment by cjlee1** [comment]
I believe I rm'd the migration scripts in my last commit so it shouldnt change

**Pull request merged**
